### PR TITLE
Fix missing parameter template and support for dots in method names

### PR DESCRIPTION
**Pull request by f03el**

### CODE REVIEW

**Comment by f03el** [comment]
I'm on a CentOS 6.5 machine with GCC 4.4.7.

**Comment by cinemast** [comment]
This crashes the build. I will have to review that. Or you can try to fix it.

**Comment by f03el** [comment]
In order to locate the error I ran the tests it fails at connector_http:

    unknown location(0): fatal error in "test_http_server_longpost": std::exception: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out

When I comment out `client.SetTimeout(-1);` (test_connector.hpp:191) it works (having only the first commit checked out).

**Comment by f03el** [comment]
Regarding the other error, I see why it fails. `testspec6.json` has method names containing dots, and the test is expecting to find a client stub with normalized method names but a server stub with raw method names. For example is the following line expected but not found in the stub server:

    virtual std::string test.method(const std::string& name) = 0;

When I didn't get my code working with a stub containing this kind of method calls I assumed that the cause was that the method names weren't correctly normalized when generating the server stub. If the approach with objects having the methods is intended (which the test indicates), is there any documentation on how to make a server based on a spec with method names containing dots?

**Comment by cinemast** [comment]
I thought I already fixed that. Let me check on that.

**Comment by cinemast** [comment]
Thank you for reporting, I added you to the AUTHORS.md

**Comment by f03el** [comment]
Great, thanks!

**Pull request closed without merging**
