### PR TITLE
fixed fd leak

### PR DESCRIPTION
**Pull request by skyfireitdiy**

### CODE REVIEW

**Comment by laudrup** [comment]
While this most likely fixes the leaks, it still requires to manually call `closesocket` the right places which is quite error prone.

Instead, I'd suggest creating a simple RAII wrapper around the file descriptor that closes the file descriptor in the destructor.

If C++11 is required anyway, this can simply be `std::unique_ptr` with a custom deleter. Let me know if you need an example of how this could be done (with or without C++11).

Note that I'm not in any way a maintainer of this library, just wanted to share my thoughts.

**Comment by skyfireitdiy** [comment]
感谢你的回复，目前我只是从我们目前项目来考虑，做最简单的修改。
如果使用unique_ptr在控制对象的生命周期确实会更好一些。


Thank you for your reply. At present, I just consider our current project and make the simplest modification.
It would be better if you use unique_ptr to control the life cycle of the object.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by skyfireitdiy** [comment]
> While this most likely fixes the leaks, it still requires to manually call `closesocket` the right places which is quite error prone.
> 
> Instead, I'd suggest creating a simple RAII wrapper around the file descriptor that closes the file descriptor in the destructor.
> 
> If C++11 is required anyway, this can simply be `std::unique_ptr` with a custom deleter. Let me know if you need an example of how this could be done (with or without C++11).
> 
> Note that I'm not in any way a maintainer of this library, just wanted to share my thoughts.

I'm too busy these days, would you like to take the time to fix this fd leak?

**Comment by cinemast** [comment]
@laudrup  I totally agree. The project requires some love in general. I will keep it in mind, thanks!

@skyfireitdiy thanks for opening the PRs.

**Pull request merged**
