### PR TITLE
Gentoo-originating build system fixes

### PR DESCRIPTION
**Pull request by mgorny**
So far:
1. `LIB_SUFFIX` support to build correctly on multilib systems,
2. `abstractstubserver.h` typo fix for consistency and reduced confusion,
3. fixed tests to be buildable with examples disabled (#101),
4. switched to regular cmake shared/static lib build (#99),
5. solved the issue of stubs being rebuild on every run.

### CODE REVIEW

**Comment by mgorny** [comment]
Ok, that should be all fixes I can think of right now :).

**Comment by debris** [comment]
I haven't run this yet, but generally looks good to me ;)

**Comment by cinemast** [comment]
@mgorny thank you for all your contributions. I already gave up on the rebuilding of generated files :D. Haven't tested it yet just looked quickly through your commits. Great work, thanks :+1:!

I will have to review and test it in more detail tomorrow. Especially the remove of the static lib version. I think it would be a good idea to switch it off/on independently. I agree with that.
The current version just made the debian packaging easier for me, because shared and static lib were compiled in a single `make all` invocation.

A few more wishes from me:
- Would you be able to raise that PR against the develop branch?
- Please add yourself to the https://github.com/cinemast/libjson-rpc-cpp/blob/master/AUTHORS.md
- Please document your changes in the Changelog

Thanks again :)

**Comment by mgorny** [comment]
Ok, updated AUTHORS and CHANGELOG as well as I could, and opened #102. Not sure how the two branches are developed, so leaving this open in case the changes can end up being backported independently.

**Comment by cinemast** [comment]
Thank you for rebasing to develop. After all issues are fixed, develop will soon become merged into the new master and 0.5 will get released.

**Pull request closed without merging**
