### PR TITLE
Add support for Hunter package manager

### LINKED ISSUE #194: CMake: export package config file
Create and install CMake config file for json-rpc-cpp package to make it available to other CMake projects via `find_package(json-rpc-cpp CONFIG)`.

Documentation what has to be done: https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html#creating-packages.

### PR DESCRIPTION
**Pull request by chfast**
Resolves #194.

### CODE REVIEW

**Comment by chfast** [comment]
@cinemast any opinion about this?

**Comment by cinemast** [comment]
@chfast sorry for the late response. I always wanted to give hunter a lock. Thanks for your contributions.

**Comment by chfast** [comment]
Awesome!
Is there a change to release this? Then we would be able to point this release directly in Hunter.

**Comment by cinemast** [comment]
I'm currently working on that. A lot of stuff has queued up in the last 6 months. I hope I'll get it done this week.

**Pull request merged**
