### PR TITLE
Fix tcp socket client

### PR DESCRIPTION
**Pull request by tvannoy**
The tcp socket clients included tcpsocketclientprivate.h, which cmake didn't add to the libraries include directory. As a result, applications wouldn't compile outside of the src/examples directory. I removed tcpsocketclientprivate.h, and instead made the clients inherit directly from IClientConnector, similar to how the tcp socket servers inherit from AbstractServerConnector. 

I also converted some lingering tabs to 4 spaces. 

Socket clients can now be written and compiled in any directory.

### CODE REVIEW

**Comment by tvannoy** [comment]
For what it's worth, this issue likely could have been solved by adding tcpsocketclientprivate.h to the cmake list; if that's preferred, I can rework the PR.

**Comment by cinemast** [comment]
Thanks!

**Comment by cinemast** [comment]
I didn't like the *private.h thing anyway.

**Comment by tvannoy** [comment]
Thanks for merging! I agree, the *private.h architecture didn't seem quite as clean, although I think I understand the original author's intent.

**Pull request merged**
