### PR TITLE
README: add instructions for Fedora

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by cinemast** [comment]
Great! Did not know it was also available in fedora. Thanks!

**Comment by ignatenkobrain** [comment]
I made it available in https://koji.fedoraproject.org/koji/buildinfo?buildID=835704 since Mon, 23 Jan 2017 14:14:29 UTC ;)

**Comment by cinemast** [comment]
Thank you! Could you update to the latest version?

**Comment by ignatenkobrain** [comment]
@cinemast it's already 1.0.0 since Mon, 28 Aug 2017 06:27:31 UTC :P

**Comment by cinemast** [comment]
Well thanks then :D

**Pull request merged**
