### PR TITLE
Added new boost::beast HTTP server/client connectors

### PR DESCRIPTION
**Pull request by mr-j0nes**
Added new beast connectors.

### CODE REVIEW

**Comment by cinemast** [comment]
Sorry for taking so long to review this and thanks for your contribution.

Which boost version did you use to build/test this? 
On OSX (boost version 1.70) I get the following compile errors: 

```
/Users/cinemast/git/github/libjson-rpc-cpp/src/jsonrpccpp/server/connectors/beasthttpserver.cpp:24:7: error:
      no matching constructor for initialization of
      'boost::asio::strand<boost::asio::io_context::executor_type>'
    , strand_(socket_.get_executor())
      ^       ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/strand.hpp:48:12: note: candidate constructor not
      viable: no known conversion from
      'boost::asio::basic_socket<boost::asio::ip::tcp,
      boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to
      'const boost::asio::io_context::executor_type' for 1st argument
  explicit strand(const Executor& e)
           ^
/usr/local/include/boost/asio/strand.hpp:56:3: note: candidate constructor not
      viable: no known conversion from
      'boost::asio::basic_socket<boost::asio::ip::tcp,
      boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to
      'const boost::asio::strand<boost::asio::io_context::executor_type>' for
      1st argument
  strand(const strand& other) BOOST_ASIO_NOEXCEPT
  ^
/usr/local/include/boost/asio/strand.hpp:99:3: note: candidate constructor not
      viable: no known conversion from
      'boost::asio::basic_socket<boost::asio::ip::tcp,
      boost::asio::executor>::executor_type' (aka 'boost::asio::executor') to
      'boost::asio::strand<boost::asio::io_context::executor_type>' for 1st
      argument
  strand(strand&& other) BOOST_ASIO_NOEXCEPT
  ^
/usr/local/include/boost/asio/strand.hpp:68:3: note: candidate template ignored:
      could not match 'strand<type-parameter-0-0>' against
      'boost::asio::executor'
  strand(
  ^
/usr/local/include/boost/asio/strand.hpp:111:3: note: candidate template
      ignored: could not match 'strand<type-parameter-0-0>' against
      'boost::asio::executor'
  strand(strand<OtherExecutor>&& other) BOOST_ASIO_NOEXCEPT
  ^
/usr/local/include/boost/asio/strand.hpp:40:3: note: candidate constructor not
      viable: requires 0 arguments, but 1 was provided
  strand()
  ^
1 error generated.
```

**Comment by cinemast** [comment]
Also to avoid code rotting, please enable the connectors and their testing in the travis build

**Comment by cinemast** [comment]
Sorry I should have been more clear on this. Please don't enable them by default, but rather as command line parameters in [here](https://github.com/cinemast/libjson-rpc-cpp/blob/master/docker/build_test_install.sh#L16)

**Comment by mr-j0nes** [comment]
Ok sorry, I'll do it that way. To answer your previous question.I use boost version 1.69...

**Comment by cinemast** [comment]
No problem, I am looking forward to the fixes.

**Comment by mr-j0nes** [comment]
Ok added version to boost 1.70. I don't see errors, let me know if you do...

**Comment by mr-j0nes** [comment]
Is there something else I have to do here ?

**Comment by cinemast** [comment]
Could you open a new pullrequest regarding this? For some reason Travis no longer wants to builds here. Sorry I missed your comment here.

**Comment by mr-j0nes** [comment]
Since now I use json-rpc-cxx, I think cpp-httplib is a more elegant option to Beast. Therefore dismissing this..

**Comment by cinemast** [comment]
Good to hear! Thanks for your efforts.

**Pull request closed without merging**
