### PR TITLE
one server - multiple connectors

### PR DESCRIPTION
**Pull request by artkuznetsov101**
Sometimes you need to add several AbstractServerConnector implementations to your abstract server stub (for example, jsonrpc::HttpServer AND jsonrpc::TcpSocketServer, or  jsonrpc::HttpServer AND "my custom" server)

### CODE REVIEW

**Comment by cinemast** [comment]
Hi I'd love to see this feature, but I would like to implement it differently.
Instead of adding multiple connectors to the server, I'd suggest adding multiple servers to a connector. This way it is more transparent and it would no longer violate inverse dependencies between connector and server.

This way it would also be more flexible.
What do you think abbout it?

**Comment by artkuznetsov101** [comment]
To clarify the situation.
My project consist of custom self-implemented (JMS-like) connector and generated server stub (jsonrpc::AbstractServer<MySuperServerFuncton>) as backend. In my PR I tried to find a way to add one more connector (jsonrpc::HttpServer) to get multi-protocol (JMS + http) server stub with one backend.

And if I get you right, you suggest something like this:

`MyStubServer stub(); //not implemented constructor`

`JMSServer jmsserver(61616);`
`jmsserver.addServer(stub); //not implemented method`

`HttpServer httpserver(8383);`
`httpserver.addServer(stub); //not implemented method`

`stub.StartListening();`

**Comment by cinemast** [comment]
Hi! 

That's exactly what I had in mind, except for the `stub.StartListening()`, it should be a `jmsserver.StartListening()` and `httpserver.StartListening()`.

**Comment by cinemast** [comment]
Closes #183

**Comment by cinemast** [comment]
@artkuznetsov101 any progress on this? I could also finish it, just need to know so no effort is wasted.

**Comment by artkuznetsov101** [comment]
@cinemast So, ok. Let's close my PR.

**Pull request closed without merging**
