### PR TITLE
Visual Studio Improvements

### PR DESCRIPTION
**Pull request by SE2Dev**
Resolves several CMake issues
Adds Visual Studio files to .gitignore
Resolved a header issue when compiling SimpleServer with Visual Studio
Disabled POSIX deprecation
etc.

### CODE REVIEW

**Comment by cinemast** [comment]
Please revert the line-ending changes.

**Comment by SE2Dev** [comment]
Would you prefer that I removed or redid the commits that initially changed the line endings, or do you want me to just add a commit that changes them back?

**Comment by cinemast** [comment]
Sinc this pull request has been inactive for a long time, I will close it for now. Feel free to reopen again.

**Comment by SE2Dev** [comment]
I'll look into it again when I get the chance. I kinda kept putting it off because of the weird issues I kept seeing with libcurl not working properly on Windows; I'm not sure if they've fixed the issue since then or not.

**Pull request closed without merging**
