### PR TITLE
Added a dockerfile to generate the android version to  libjson-rpc-cpp

### PR DESCRIPTION
**Pull request by gogo40**
HI @cinemast ,

I created a small dockerfile to generate the android libraries to libjson-rpc-cpp. I added a shell script in docker/build_android_libs.sh that create the docker image and copy the generated libraries to docker/output.

### CODE REVIEW

**Comment by cinemast** [comment]
That is a great idea. Can you add a little documentation for this (how to use it).

**Comment by gogo40** [comment]
Hi, @cinemast !

Yeah, I do. But, currently, I don't know why my app is broken in android. I can prepare other Dockerfile to generate the linux libraries and the windows libraries (using cross-compilling, via mingw32).

**Comment by cinemast** [comment]
That sounds great :+1:

**Comment by cinemast** [comment]
Short ping on that. Do you plan to extend your dockerfile? Last status was, that it is broken, right?

Otherwise I would like to close this pull-request for now.

**Comment by gogo40** [comment]
Hi @cinemast , I'll prepare other Dockerfile to compile a linux version in a docker container. You can close this pull request, because I'll send other PR with the correct Dockerfile to linux.

**Comment by cinemast** [comment]
Thank you!

**Pull request closed without merging**
