### PR TITLE
PR fixing issue #141

### PR DESCRIPTION
**Pull request by EricLagergren**
See https://github.com/cinemast/libjson-rpc-cpp/issues/141#issue-119270786

### CODE REVIEW

**Comment by EricLagergren** [comment]
See https://github.com/cinemast/libjson-rpc-cpp/issues/141#issuecomment-160361853

**Comment by EricLagergren** [comment]
Unsure why, but if `Json::Value` was an integer, `Json::Value::asString()` would work locally but fail on Travis CI. So, in the test I changed so it compares integers instead of strings. /shrug

**Comment by cinemast** [comment]
Sorry for waiting so long. I reviewed your changes now. Thank you very much for your contribution.

**Comment by EricLagergren** [comment]
you're welcome!

**Pull request merged**
