### PR TITLE
jsonrpc for msvc

### PR DESCRIPTION
**Pull request by debris**
common, client && server compiling in msvc (release mode)

i've tested compiling with

cmake 3.0.2
MSVC 2013 Community

```bash
cmake -DCMAKE_PREFIX_PATH=path_to_dependencies -DCOMPILE_STUBGEN=NO -DCOMPILE_TESTS=NO ..
```

##### fixed:

* [fixed recognition of JSONCPP_INCLUDE_PREFIX](https://github.com/debris/libjson-rpc-cpp/blob/jsonrpc4msvc/cmake/FindJSONCPP.cmake#L28)
  * I was still using 'old' jsoncpp and I had `version.h` file. This caused configuration fail.
* added [include_directories from custom CMAKE_PREFIX_PATH](https://github.com/debris/libjson-rpc-cpp/blob/jsonrpc4msvc/CMakeLists.txt#L27)
  * this should solve some of the issues with custom dependencies path. Ideally, ```include_directories(XXX_INCLUDE_DIRS)``` should be used
* findCURL now supports `libcurl` library name
* findMHD now supports `libmicrohttpd` and `libmicrohttpd-dll`
  * these are the names of libraries created from [libmicrohttpd repo](https://github.com/svn2github/libmicrohttpd)
* removed dependency on `unistd.h`
  * I replaced `usleep(timeout*1000);` with `std::this_thread::sleep_for(std::chrono::microseconds(timeout*1000))`
* fixed compilation order in msvc [here](https://github.com/debris/libjson-rpc-cpp/blob/jsonrpc4msvc/src/jsonrpccpp/CMakeLists.txt#L71) and [here](https://github.com/debris/libjson-rpc-cpp/blob/jsonrpc4msvc/src/jsonrpccpp/CMakeLists.txt#L80)

##### still todo: 
* compiling in debug mode (probably in next pr)
* compiling stubgen, tests
* fixing style issues (cmake style is inconsistent between files, 2 spaces, 4 spaces, tabs...)

### CODE REVIEW

**Comment by cinemast** [comment]
Hi!

It is great that you are working on msvc support. Travis does not like the new sleep commands. If #ifdef could be avoided, it would be great, if not I am OK with that.

I am aware that the CMakeFiles are not very well written and there is some ugly stuff (especially for the win32 cases) in them. I am very happy about contributions in this direction.

**Comment by debris** [comment]
* i've added -std=c++11 flag to cland/gcc build options
* i've upgraded travis-ci gcc version to 4.8
* coveralls should be working fine now (i've added gcov path)

**Comment by cinemast** [comment]
Apparently my last comment got lost. 

Thank you again for your effort on porting this to msvc. I reviewed your latest changes. I am not sure if it is worth dropping non C++11 support just for a sleep? Maybe we are better of here with a `#ifdef`?

You saw how much effort it is to port it to Ubuntu 12.04, which I still consider as main platform along with Debian Wheezy. 

Could you bring back non C++11 support?

**Comment by debris** [comment]
sure

**Comment by debris** [comment]
I've replaced c++11 with `#if`s.

**Comment by cinemast** [comment]
Great! Please also revert the changes to travis.yml where you install gcc 4.8.

**Comment by debris** [comment]
I already reverted them, by pushing with force and overwriting unnecessary commits.

**Comment by cinemast** [comment]
Can this one be closed, as it is a subset of #90?

**Comment by debris** [comment]
sure!

**Pull request closed without merging**
